// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ai.proto

package com.reis.game.resource.prototype;

public final class AI {
  private AI() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AIDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AIData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    java.util.List<com.reis.game.resource.prototype.AI.Waypoint> 
        getWaypointList();
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    com.reis.game.resource.prototype.AI.Waypoint getWaypoint(int index);
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    int getWaypointCount();
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    java.util.List<? extends com.reis.game.resource.prototype.AI.WaypointOrBuilder> 
        getWaypointOrBuilderList();
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    com.reis.game.resource.prototype.AI.WaypointOrBuilder getWaypointOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code AIData}
   */
  public  static final class AIData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AIData)
      AIDataOrBuilder {
    // Use AIData.newBuilder() to construct.
    private AIData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AIData() {
      waypoint_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AIData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                waypoint_ = new java.util.ArrayList<com.reis.game.resource.prototype.AI.Waypoint>();
                mutable_bitField0_ |= 0x00000001;
              }
              waypoint_.add(
                  input.readMessage(com.reis.game.resource.prototype.AI.Waypoint.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          waypoint_ = java.util.Collections.unmodifiableList(waypoint_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.AI.internal_static_AIData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.AI.internal_static_AIData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.AI.AIData.class, com.reis.game.resource.prototype.AI.AIData.Builder.class);
    }

    public static final int WAYPOINT_FIELD_NUMBER = 1;
    private java.util.List<com.reis.game.resource.prototype.AI.Waypoint> waypoint_;
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    public java.util.List<com.reis.game.resource.prototype.AI.Waypoint> getWaypointList() {
      return waypoint_;
    }
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    public java.util.List<? extends com.reis.game.resource.prototype.AI.WaypointOrBuilder> 
        getWaypointOrBuilderList() {
      return waypoint_;
    }
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    public int getWaypointCount() {
      return waypoint_.size();
    }
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    public com.reis.game.resource.prototype.AI.Waypoint getWaypoint(int index) {
      return waypoint_.get(index);
    }
    /**
     * <code>repeated .Waypoint waypoint = 1;</code>
     */
    public com.reis.game.resource.prototype.AI.WaypointOrBuilder getWaypointOrBuilder(
        int index) {
      return waypoint_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < waypoint_.size(); i++) {
        output.writeMessage(1, waypoint_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < waypoint_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, waypoint_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.AI.AIData)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.AI.AIData other = (com.reis.game.resource.prototype.AI.AIData) obj;

      boolean result = true;
      result = result && getWaypointList()
          .equals(other.getWaypointList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getWaypointCount() > 0) {
        hash = (37 * hash) + WAYPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getWaypointList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.AI.AIData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AI.AIData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.AI.AIData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AIData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AIData)
        com.reis.game.resource.prototype.AI.AIDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.AI.internal_static_AIData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.AI.internal_static_AIData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.AI.AIData.class, com.reis.game.resource.prototype.AI.AIData.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.AI.AIData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getWaypointFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (waypointBuilder_ == null) {
          waypoint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          waypointBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.AI.internal_static_AIData_descriptor;
      }

      public com.reis.game.resource.prototype.AI.AIData getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.AI.AIData.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.AI.AIData build() {
        com.reis.game.resource.prototype.AI.AIData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.AI.AIData buildPartial() {
        com.reis.game.resource.prototype.AI.AIData result = new com.reis.game.resource.prototype.AI.AIData(this);
        int from_bitField0_ = bitField0_;
        if (waypointBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            waypoint_ = java.util.Collections.unmodifiableList(waypoint_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.waypoint_ = waypoint_;
        } else {
          result.waypoint_ = waypointBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.AI.AIData) {
          return mergeFrom((com.reis.game.resource.prototype.AI.AIData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.AI.AIData other) {
        if (other == com.reis.game.resource.prototype.AI.AIData.getDefaultInstance()) return this;
        if (waypointBuilder_ == null) {
          if (!other.waypoint_.isEmpty()) {
            if (waypoint_.isEmpty()) {
              waypoint_ = other.waypoint_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureWaypointIsMutable();
              waypoint_.addAll(other.waypoint_);
            }
            onChanged();
          }
        } else {
          if (!other.waypoint_.isEmpty()) {
            if (waypointBuilder_.isEmpty()) {
              waypointBuilder_.dispose();
              waypointBuilder_ = null;
              waypoint_ = other.waypoint_;
              bitField0_ = (bitField0_ & ~0x00000001);
              waypointBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getWaypointFieldBuilder() : null;
            } else {
              waypointBuilder_.addAllMessages(other.waypoint_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.AI.AIData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.AI.AIData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.reis.game.resource.prototype.AI.Waypoint> waypoint_ =
        java.util.Collections.emptyList();
      private void ensureWaypointIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          waypoint_ = new java.util.ArrayList<com.reis.game.resource.prototype.AI.Waypoint>(waypoint_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.AI.Waypoint, com.reis.game.resource.prototype.AI.Waypoint.Builder, com.reis.game.resource.prototype.AI.WaypointOrBuilder> waypointBuilder_;

      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.AI.Waypoint> getWaypointList() {
        if (waypointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(waypoint_);
        } else {
          return waypointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public int getWaypointCount() {
        if (waypointBuilder_ == null) {
          return waypoint_.size();
        } else {
          return waypointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public com.reis.game.resource.prototype.AI.Waypoint getWaypoint(int index) {
        if (waypointBuilder_ == null) {
          return waypoint_.get(index);
        } else {
          return waypointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder setWaypoint(
          int index, com.reis.game.resource.prototype.AI.Waypoint value) {
        if (waypointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaypointIsMutable();
          waypoint_.set(index, value);
          onChanged();
        } else {
          waypointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder setWaypoint(
          int index, com.reis.game.resource.prototype.AI.Waypoint.Builder builderForValue) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.set(index, builderForValue.build());
          onChanged();
        } else {
          waypointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder addWaypoint(com.reis.game.resource.prototype.AI.Waypoint value) {
        if (waypointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaypointIsMutable();
          waypoint_.add(value);
          onChanged();
        } else {
          waypointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder addWaypoint(
          int index, com.reis.game.resource.prototype.AI.Waypoint value) {
        if (waypointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureWaypointIsMutable();
          waypoint_.add(index, value);
          onChanged();
        } else {
          waypointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder addWaypoint(
          com.reis.game.resource.prototype.AI.Waypoint.Builder builderForValue) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.add(builderForValue.build());
          onChanged();
        } else {
          waypointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder addWaypoint(
          int index, com.reis.game.resource.prototype.AI.Waypoint.Builder builderForValue) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.add(index, builderForValue.build());
          onChanged();
        } else {
          waypointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder addAllWaypoint(
          java.lang.Iterable<? extends com.reis.game.resource.prototype.AI.Waypoint> values) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, waypoint_);
          onChanged();
        } else {
          waypointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder clearWaypoint() {
        if (waypointBuilder_ == null) {
          waypoint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          waypointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public Builder removeWaypoint(int index) {
        if (waypointBuilder_ == null) {
          ensureWaypointIsMutable();
          waypoint_.remove(index);
          onChanged();
        } else {
          waypointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public com.reis.game.resource.prototype.AI.Waypoint.Builder getWaypointBuilder(
          int index) {
        return getWaypointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public com.reis.game.resource.prototype.AI.WaypointOrBuilder getWaypointOrBuilder(
          int index) {
        if (waypointBuilder_ == null) {
          return waypoint_.get(index);  } else {
          return waypointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public java.util.List<? extends com.reis.game.resource.prototype.AI.WaypointOrBuilder> 
           getWaypointOrBuilderList() {
        if (waypointBuilder_ != null) {
          return waypointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(waypoint_);
        }
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public com.reis.game.resource.prototype.AI.Waypoint.Builder addWaypointBuilder() {
        return getWaypointFieldBuilder().addBuilder(
            com.reis.game.resource.prototype.AI.Waypoint.getDefaultInstance());
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public com.reis.game.resource.prototype.AI.Waypoint.Builder addWaypointBuilder(
          int index) {
        return getWaypointFieldBuilder().addBuilder(
            index, com.reis.game.resource.prototype.AI.Waypoint.getDefaultInstance());
      }
      /**
       * <code>repeated .Waypoint waypoint = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.AI.Waypoint.Builder> 
           getWaypointBuilderList() {
        return getWaypointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.AI.Waypoint, com.reis.game.resource.prototype.AI.Waypoint.Builder, com.reis.game.resource.prototype.AI.WaypointOrBuilder> 
          getWaypointFieldBuilder() {
        if (waypointBuilder_ == null) {
          waypointBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.reis.game.resource.prototype.AI.Waypoint, com.reis.game.resource.prototype.AI.Waypoint.Builder, com.reis.game.resource.prototype.AI.WaypointOrBuilder>(
                  waypoint_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          waypoint_ = null;
        }
        return waypointBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:AIData)
    }

    // @@protoc_insertion_point(class_scope:AIData)
    private static final com.reis.game.resource.prototype.AI.AIData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.AI.AIData();
    }

    public static com.reis.game.resource.prototype.AI.AIData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AIData>
        PARSER = new com.google.protobuf.AbstractParser<AIData>() {
      public AIData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AIData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AIData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AIData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.AI.AIData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WaypointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Waypoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 x = 1;</code>
     */
    int getX();

    /**
     * <code>optional int32 y = 2;</code>
     */
    int getY();
  }
  /**
   * Protobuf type {@code Waypoint}
   */
  public  static final class Waypoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Waypoint)
      WaypointOrBuilder {
    // Use Waypoint.newBuilder() to construct.
    private Waypoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Waypoint() {
      x_ = 0;
      y_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Waypoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              x_ = input.readInt32();
              break;
            }
            case 16: {

              y_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.AI.internal_static_Waypoint_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.AI.internal_static_Waypoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.AI.Waypoint.class, com.reis.game.resource.prototype.AI.Waypoint.Builder.class);
    }

    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    /**
     * <code>optional int32 x = 1;</code>
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    /**
     * <code>optional int32 y = 2;</code>
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (x_ != 0) {
        output.writeInt32(1, x_);
      }
      if (y_ != 0) {
        output.writeInt32(2, y_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.AI.Waypoint)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.AI.Waypoint other = (com.reis.game.resource.prototype.AI.Waypoint) obj;

      boolean result = true;
      result = result && (getX()
          == other.getX());
      result = result && (getY()
          == other.getY());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AI.Waypoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.AI.Waypoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Waypoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Waypoint)
        com.reis.game.resource.prototype.AI.WaypointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.AI.internal_static_Waypoint_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.AI.internal_static_Waypoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.AI.Waypoint.class, com.reis.game.resource.prototype.AI.Waypoint.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.AI.Waypoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        x_ = 0;

        y_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.AI.internal_static_Waypoint_descriptor;
      }

      public com.reis.game.resource.prototype.AI.Waypoint getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.AI.Waypoint.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.AI.Waypoint build() {
        com.reis.game.resource.prototype.AI.Waypoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.AI.Waypoint buildPartial() {
        com.reis.game.resource.prototype.AI.Waypoint result = new com.reis.game.resource.prototype.AI.Waypoint(this);
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.AI.Waypoint) {
          return mergeFrom((com.reis.game.resource.prototype.AI.Waypoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.AI.Waypoint other) {
        if (other == com.reis.game.resource.prototype.AI.Waypoint.getDefaultInstance()) return this;
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.AI.Waypoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.AI.Waypoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int x_ ;
      /**
       * <code>optional int32 x = 1;</code>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 x = 1;</code>
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>optional int32 y = 2;</code>
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 y = 2;</code>
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Waypoint)
    }

    // @@protoc_insertion_point(class_scope:Waypoint)
    private static final com.reis.game.resource.prototype.AI.Waypoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.AI.Waypoint();
    }

    public static com.reis.game.resource.prototype.AI.Waypoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Waypoint>
        PARSER = new com.google.protobuf.AbstractParser<Waypoint>() {
      public Waypoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Waypoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Waypoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Waypoint> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.AI.Waypoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AIData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AIData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Waypoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Waypoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\010ai.proto\"%\n\006AIData\022\033\n\010waypoint\030\001 \003(\0132\t" +
      ".Waypoint\" \n\010Waypoint\022\t\n\001x\030\001 \001(\005\022\t\n\001y\030\002 " +
      "\001(\005B&\n com.reis.game.resource.prototypeB" +
      "\002AIb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AIData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AIData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AIData_descriptor,
        new java.lang.String[] { "Waypoint", });
    internal_static_Waypoint_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Waypoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Waypoint_descriptor,
        new java.lang.String[] { "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
