// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: animation.proto

package com.reis.game.resource.prototype;

public final class AnimationProto {
  private AnimationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AnimationDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AnimationData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    java.util.List<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype> 
        getAnimationPrototypeList();
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getAnimationPrototype(int index);
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    int getAnimationPrototypeCount();
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    java.util.List<? extends com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder> 
        getAnimationPrototypeOrBuilderList();
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder getAnimationPrototypeOrBuilder(
        int index);

    /**
     * <code>.AnimationPrototype defaultAnimation = 2;</code>
     */
    boolean hasDefaultAnimation();
    /**
     * <code>.AnimationPrototype defaultAnimation = 2;</code>
     */
    com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getDefaultAnimation();
    /**
     * <code>.AnimationPrototype defaultAnimation = 2;</code>
     */
    com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder getDefaultAnimationOrBuilder();
  }
  /**
   * Protobuf type {@code AnimationData}
   */
  public  static final class AnimationData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AnimationData)
      AnimationDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnimationData.newBuilder() to construct.
    private AnimationData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnimationData() {
      animationPrototype_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnimationData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                animationPrototype_ = new java.util.ArrayList<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype>();
                mutable_bitField0_ |= 0x00000001;
              }
              animationPrototype_.add(
                  input.readMessage(com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.parser(), extensionRegistry));
              break;
            }
            case 18: {
              com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder subBuilder = null;
              if (defaultAnimation_ != null) {
                subBuilder = defaultAnimation_.toBuilder();
              }
              defaultAnimation_ = input.readMessage(com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(defaultAnimation_);
                defaultAnimation_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          animationPrototype_ = java.util.Collections.unmodifiableList(animationPrototype_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.AnimationProto.AnimationData.class, com.reis.game.resource.prototype.AnimationProto.AnimationData.Builder.class);
    }

    private int bitField0_;
    public static final int ANIMATIONPROTOTYPE_FIELD_NUMBER = 1;
    private java.util.List<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype> animationPrototype_;
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    public java.util.List<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype> getAnimationPrototypeList() {
      return animationPrototype_;
    }
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    public java.util.List<? extends com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder> 
        getAnimationPrototypeOrBuilderList() {
      return animationPrototype_;
    }
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    public int getAnimationPrototypeCount() {
      return animationPrototype_.size();
    }
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getAnimationPrototype(int index) {
      return animationPrototype_.get(index);
    }
    /**
     * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
     */
    public com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder getAnimationPrototypeOrBuilder(
        int index) {
      return animationPrototype_.get(index);
    }

    public static final int DEFAULTANIMATION_FIELD_NUMBER = 2;
    private com.reis.game.resource.prototype.AnimationProto.AnimationPrototype defaultAnimation_;
    /**
     * <code>.AnimationPrototype defaultAnimation = 2;</code>
     */
    public boolean hasDefaultAnimation() {
      return defaultAnimation_ != null;
    }
    /**
     * <code>.AnimationPrototype defaultAnimation = 2;</code>
     */
    public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getDefaultAnimation() {
      return defaultAnimation_ == null ? com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.getDefaultInstance() : defaultAnimation_;
    }
    /**
     * <code>.AnimationPrototype defaultAnimation = 2;</code>
     */
    public com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder getDefaultAnimationOrBuilder() {
      return getDefaultAnimation();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < animationPrototype_.size(); i++) {
        output.writeMessage(1, animationPrototype_.get(i));
      }
      if (defaultAnimation_ != null) {
        output.writeMessage(2, getDefaultAnimation());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < animationPrototype_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, animationPrototype_.get(i));
      }
      if (defaultAnimation_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDefaultAnimation());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.AnimationProto.AnimationData)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.AnimationProto.AnimationData other = (com.reis.game.resource.prototype.AnimationProto.AnimationData) obj;

      boolean result = true;
      result = result && getAnimationPrototypeList()
          .equals(other.getAnimationPrototypeList());
      result = result && (hasDefaultAnimation() == other.hasDefaultAnimation());
      if (hasDefaultAnimation()) {
        result = result && getDefaultAnimation()
            .equals(other.getDefaultAnimation());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAnimationPrototypeCount() > 0) {
        hash = (37 * hash) + ANIMATIONPROTOTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getAnimationPrototypeList().hashCode();
      }
      if (hasDefaultAnimation()) {
        hash = (37 * hash) + DEFAULTANIMATION_FIELD_NUMBER;
        hash = (53 * hash) + getDefaultAnimation().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.AnimationProto.AnimationData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnimationData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AnimationData)
        com.reis.game.resource.prototype.AnimationProto.AnimationDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.AnimationProto.AnimationData.class, com.reis.game.resource.prototype.AnimationProto.AnimationData.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.AnimationProto.AnimationData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAnimationPrototypeFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (animationPrototypeBuilder_ == null) {
          animationPrototype_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          animationPrototypeBuilder_.clear();
        }
        if (defaultAnimationBuilder_ == null) {
          defaultAnimation_ = null;
        } else {
          defaultAnimation_ = null;
          defaultAnimationBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationData_descriptor;
      }

      public com.reis.game.resource.prototype.AnimationProto.AnimationData getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.AnimationProto.AnimationData.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.AnimationProto.AnimationData build() {
        com.reis.game.resource.prototype.AnimationProto.AnimationData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.AnimationProto.AnimationData buildPartial() {
        com.reis.game.resource.prototype.AnimationProto.AnimationData result = new com.reis.game.resource.prototype.AnimationProto.AnimationData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (animationPrototypeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            animationPrototype_ = java.util.Collections.unmodifiableList(animationPrototype_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.animationPrototype_ = animationPrototype_;
        } else {
          result.animationPrototype_ = animationPrototypeBuilder_.build();
        }
        if (defaultAnimationBuilder_ == null) {
          result.defaultAnimation_ = defaultAnimation_;
        } else {
          result.defaultAnimation_ = defaultAnimationBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.AnimationProto.AnimationData) {
          return mergeFrom((com.reis.game.resource.prototype.AnimationProto.AnimationData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.AnimationProto.AnimationData other) {
        if (other == com.reis.game.resource.prototype.AnimationProto.AnimationData.getDefaultInstance()) return this;
        if (animationPrototypeBuilder_ == null) {
          if (!other.animationPrototype_.isEmpty()) {
            if (animationPrototype_.isEmpty()) {
              animationPrototype_ = other.animationPrototype_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAnimationPrototypeIsMutable();
              animationPrototype_.addAll(other.animationPrototype_);
            }
            onChanged();
          }
        } else {
          if (!other.animationPrototype_.isEmpty()) {
            if (animationPrototypeBuilder_.isEmpty()) {
              animationPrototypeBuilder_.dispose();
              animationPrototypeBuilder_ = null;
              animationPrototype_ = other.animationPrototype_;
              bitField0_ = (bitField0_ & ~0x00000001);
              animationPrototypeBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAnimationPrototypeFieldBuilder() : null;
            } else {
              animationPrototypeBuilder_.addAllMessages(other.animationPrototype_);
            }
          }
        }
        if (other.hasDefaultAnimation()) {
          mergeDefaultAnimation(other.getDefaultAnimation());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.AnimationProto.AnimationData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.AnimationProto.AnimationData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype> animationPrototype_ =
        java.util.Collections.emptyList();
      private void ensureAnimationPrototypeIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          animationPrototype_ = new java.util.ArrayList<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype>(animationPrototype_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.AnimationProto.AnimationPrototype, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder, com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder> animationPrototypeBuilder_;

      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype> getAnimationPrototypeList() {
        if (animationPrototypeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(animationPrototype_);
        } else {
          return animationPrototypeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public int getAnimationPrototypeCount() {
        if (animationPrototypeBuilder_ == null) {
          return animationPrototype_.size();
        } else {
          return animationPrototypeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getAnimationPrototype(int index) {
        if (animationPrototypeBuilder_ == null) {
          return animationPrototype_.get(index);
        } else {
          return animationPrototypeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder setAnimationPrototype(
          int index, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype value) {
        if (animationPrototypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimationPrototypeIsMutable();
          animationPrototype_.set(index, value);
          onChanged();
        } else {
          animationPrototypeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder setAnimationPrototype(
          int index, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder builderForValue) {
        if (animationPrototypeBuilder_ == null) {
          ensureAnimationPrototypeIsMutable();
          animationPrototype_.set(index, builderForValue.build());
          onChanged();
        } else {
          animationPrototypeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder addAnimationPrototype(com.reis.game.resource.prototype.AnimationProto.AnimationPrototype value) {
        if (animationPrototypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimationPrototypeIsMutable();
          animationPrototype_.add(value);
          onChanged();
        } else {
          animationPrototypeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder addAnimationPrototype(
          int index, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype value) {
        if (animationPrototypeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimationPrototypeIsMutable();
          animationPrototype_.add(index, value);
          onChanged();
        } else {
          animationPrototypeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder addAnimationPrototype(
          com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder builderForValue) {
        if (animationPrototypeBuilder_ == null) {
          ensureAnimationPrototypeIsMutable();
          animationPrototype_.add(builderForValue.build());
          onChanged();
        } else {
          animationPrototypeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder addAnimationPrototype(
          int index, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder builderForValue) {
        if (animationPrototypeBuilder_ == null) {
          ensureAnimationPrototypeIsMutable();
          animationPrototype_.add(index, builderForValue.build());
          onChanged();
        } else {
          animationPrototypeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder addAllAnimationPrototype(
          java.lang.Iterable<? extends com.reis.game.resource.prototype.AnimationProto.AnimationPrototype> values) {
        if (animationPrototypeBuilder_ == null) {
          ensureAnimationPrototypeIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, animationPrototype_);
          onChanged();
        } else {
          animationPrototypeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder clearAnimationPrototype() {
        if (animationPrototypeBuilder_ == null) {
          animationPrototype_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          animationPrototypeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public Builder removeAnimationPrototype(int index) {
        if (animationPrototypeBuilder_ == null) {
          ensureAnimationPrototypeIsMutable();
          animationPrototype_.remove(index);
          onChanged();
        } else {
          animationPrototypeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder getAnimationPrototypeBuilder(
          int index) {
        return getAnimationPrototypeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder getAnimationPrototypeOrBuilder(
          int index) {
        if (animationPrototypeBuilder_ == null) {
          return animationPrototype_.get(index);  } else {
          return animationPrototypeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public java.util.List<? extends com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder> 
           getAnimationPrototypeOrBuilderList() {
        if (animationPrototypeBuilder_ != null) {
          return animationPrototypeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(animationPrototype_);
        }
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder addAnimationPrototypeBuilder() {
        return getAnimationPrototypeFieldBuilder().addBuilder(
            com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.getDefaultInstance());
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder addAnimationPrototypeBuilder(
          int index) {
        return getAnimationPrototypeFieldBuilder().addBuilder(
            index, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.getDefaultInstance());
      }
      /**
       * <code>repeated .AnimationPrototype animationPrototype = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder> 
           getAnimationPrototypeBuilderList() {
        return getAnimationPrototypeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.AnimationProto.AnimationPrototype, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder, com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder> 
          getAnimationPrototypeFieldBuilder() {
        if (animationPrototypeBuilder_ == null) {
          animationPrototypeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.reis.game.resource.prototype.AnimationProto.AnimationPrototype, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder, com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder>(
                  animationPrototype_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          animationPrototype_ = null;
        }
        return animationPrototypeBuilder_;
      }

      private com.reis.game.resource.prototype.AnimationProto.AnimationPrototype defaultAnimation_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.resource.prototype.AnimationProto.AnimationPrototype, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder, com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder> defaultAnimationBuilder_;
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public boolean hasDefaultAnimation() {
        return defaultAnimationBuilder_ != null || defaultAnimation_ != null;
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getDefaultAnimation() {
        if (defaultAnimationBuilder_ == null) {
          return defaultAnimation_ == null ? com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.getDefaultInstance() : defaultAnimation_;
        } else {
          return defaultAnimationBuilder_.getMessage();
        }
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public Builder setDefaultAnimation(com.reis.game.resource.prototype.AnimationProto.AnimationPrototype value) {
        if (defaultAnimationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          defaultAnimation_ = value;
          onChanged();
        } else {
          defaultAnimationBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public Builder setDefaultAnimation(
          com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder builderForValue) {
        if (defaultAnimationBuilder_ == null) {
          defaultAnimation_ = builderForValue.build();
          onChanged();
        } else {
          defaultAnimationBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public Builder mergeDefaultAnimation(com.reis.game.resource.prototype.AnimationProto.AnimationPrototype value) {
        if (defaultAnimationBuilder_ == null) {
          if (defaultAnimation_ != null) {
            defaultAnimation_ =
              com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.newBuilder(defaultAnimation_).mergeFrom(value).buildPartial();
          } else {
            defaultAnimation_ = value;
          }
          onChanged();
        } else {
          defaultAnimationBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public Builder clearDefaultAnimation() {
        if (defaultAnimationBuilder_ == null) {
          defaultAnimation_ = null;
          onChanged();
        } else {
          defaultAnimation_ = null;
          defaultAnimationBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder getDefaultAnimationBuilder() {
        
        onChanged();
        return getDefaultAnimationFieldBuilder().getBuilder();
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder getDefaultAnimationOrBuilder() {
        if (defaultAnimationBuilder_ != null) {
          return defaultAnimationBuilder_.getMessageOrBuilder();
        } else {
          return defaultAnimation_ == null ?
              com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.getDefaultInstance() : defaultAnimation_;
        }
      }
      /**
       * <code>.AnimationPrototype defaultAnimation = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.resource.prototype.AnimationProto.AnimationPrototype, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder, com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder> 
          getDefaultAnimationFieldBuilder() {
        if (defaultAnimationBuilder_ == null) {
          defaultAnimationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.reis.game.resource.prototype.AnimationProto.AnimationPrototype, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder, com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder>(
                  getDefaultAnimation(),
                  getParentForChildren(),
                  isClean());
          defaultAnimation_ = null;
        }
        return defaultAnimationBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AnimationData)
    }

    // @@protoc_insertion_point(class_scope:AnimationData)
    private static final com.reis.game.resource.prototype.AnimationProto.AnimationData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.AnimationProto.AnimationData();
    }

    public static com.reis.game.resource.prototype.AnimationProto.AnimationData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnimationData>
        PARSER = new com.google.protobuf.AbstractParser<AnimationData>() {
      public AnimationData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AnimationData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnimationData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnimationData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.AnimationProto.AnimationData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AnimationPrototypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AnimationPrototype)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string atlasName = 1;</code>
     */
    java.lang.String getAtlasName();
    /**
     * <code>string atlasName = 1;</code>
     */
    com.google.protobuf.ByteString
        getAtlasNameBytes();

    /**
     * <code>string animationName = 2;</code>
     */
    java.lang.String getAnimationName();
    /**
     * <code>string animationName = 2;</code>
     */
    com.google.protobuf.ByteString
        getAnimationNameBytes();

    /**
     * <code>string actionClassName = 3;</code>
     */
    java.lang.String getActionClassName();
    /**
     * <code>string actionClassName = 3;</code>
     */
    com.google.protobuf.ByteString
        getActionClassNameBytes();

    /**
     * <code>int32 entityOrientation = 4;</code>
     */
    int getEntityOrientation();

    /**
     * <code>float frameDuration = 5;</code>
     */
    float getFrameDuration();
  }
  /**
   * Protobuf type {@code AnimationPrototype}
   */
  public  static final class AnimationPrototype extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AnimationPrototype)
      AnimationPrototypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AnimationPrototype.newBuilder() to construct.
    private AnimationPrototype(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AnimationPrototype() {
      atlasName_ = "";
      animationName_ = "";
      actionClassName_ = "";
      entityOrientation_ = 0;
      frameDuration_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AnimationPrototype(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              atlasName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              animationName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              actionClassName_ = s;
              break;
            }
            case 32: {

              entityOrientation_ = input.readInt32();
              break;
            }
            case 45: {

              frameDuration_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationPrototype_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationPrototype_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.class, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder.class);
    }

    public static final int ATLASNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object atlasName_;
    /**
     * <code>string atlasName = 1;</code>
     */
    public java.lang.String getAtlasName() {
      java.lang.Object ref = atlasName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        atlasName_ = s;
        return s;
      }
    }
    /**
     * <code>string atlasName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAtlasNameBytes() {
      java.lang.Object ref = atlasName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        atlasName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANIMATIONNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object animationName_;
    /**
     * <code>string animationName = 2;</code>
     */
    public java.lang.String getAnimationName() {
      java.lang.Object ref = animationName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        animationName_ = s;
        return s;
      }
    }
    /**
     * <code>string animationName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAnimationNameBytes() {
      java.lang.Object ref = animationName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        animationName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTIONCLASSNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object actionClassName_;
    /**
     * <code>string actionClassName = 3;</code>
     */
    public java.lang.String getActionClassName() {
      java.lang.Object ref = actionClassName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionClassName_ = s;
        return s;
      }
    }
    /**
     * <code>string actionClassName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getActionClassNameBytes() {
      java.lang.Object ref = actionClassName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionClassName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ENTITYORIENTATION_FIELD_NUMBER = 4;
    private int entityOrientation_;
    /**
     * <code>int32 entityOrientation = 4;</code>
     */
    public int getEntityOrientation() {
      return entityOrientation_;
    }

    public static final int FRAMEDURATION_FIELD_NUMBER = 5;
    private float frameDuration_;
    /**
     * <code>float frameDuration = 5;</code>
     */
    public float getFrameDuration() {
      return frameDuration_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAtlasNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, atlasName_);
      }
      if (!getAnimationNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, animationName_);
      }
      if (!getActionClassNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, actionClassName_);
      }
      if (entityOrientation_ != 0) {
        output.writeInt32(4, entityOrientation_);
      }
      if (frameDuration_ != 0F) {
        output.writeFloat(5, frameDuration_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAtlasNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, atlasName_);
      }
      if (!getAnimationNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, animationName_);
      }
      if (!getActionClassNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, actionClassName_);
      }
      if (entityOrientation_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, entityOrientation_);
      }
      if (frameDuration_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, frameDuration_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.AnimationProto.AnimationPrototype)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.AnimationProto.AnimationPrototype other = (com.reis.game.resource.prototype.AnimationProto.AnimationPrototype) obj;

      boolean result = true;
      result = result && getAtlasName()
          .equals(other.getAtlasName());
      result = result && getAnimationName()
          .equals(other.getAnimationName());
      result = result && getActionClassName()
          .equals(other.getActionClassName());
      result = result && (getEntityOrientation()
          == other.getEntityOrientation());
      result = result && (
          java.lang.Float.floatToIntBits(getFrameDuration())
          == java.lang.Float.floatToIntBits(
              other.getFrameDuration()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ATLASNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAtlasName().hashCode();
      hash = (37 * hash) + ANIMATIONNAME_FIELD_NUMBER;
      hash = (53 * hash) + getAnimationName().hashCode();
      hash = (37 * hash) + ACTIONCLASSNAME_FIELD_NUMBER;
      hash = (53 * hash) + getActionClassName().hashCode();
      hash = (37 * hash) + ENTITYORIENTATION_FIELD_NUMBER;
      hash = (53 * hash) + getEntityOrientation();
      hash = (37 * hash) + FRAMEDURATION_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getFrameDuration());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.AnimationProto.AnimationPrototype prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AnimationPrototype}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AnimationPrototype)
        com.reis.game.resource.prototype.AnimationProto.AnimationPrototypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationPrototype_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationPrototype_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.class, com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        atlasName_ = "";

        animationName_ = "";

        actionClassName_ = "";

        entityOrientation_ = 0;

        frameDuration_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.AnimationProto.internal_static_AnimationPrototype_descriptor;
      }

      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype build() {
        com.reis.game.resource.prototype.AnimationProto.AnimationPrototype result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype buildPartial() {
        com.reis.game.resource.prototype.AnimationProto.AnimationPrototype result = new com.reis.game.resource.prototype.AnimationProto.AnimationPrototype(this);
        result.atlasName_ = atlasName_;
        result.animationName_ = animationName_;
        result.actionClassName_ = actionClassName_;
        result.entityOrientation_ = entityOrientation_;
        result.frameDuration_ = frameDuration_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.AnimationProto.AnimationPrototype) {
          return mergeFrom((com.reis.game.resource.prototype.AnimationProto.AnimationPrototype)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.AnimationProto.AnimationPrototype other) {
        if (other == com.reis.game.resource.prototype.AnimationProto.AnimationPrototype.getDefaultInstance()) return this;
        if (!other.getAtlasName().isEmpty()) {
          atlasName_ = other.atlasName_;
          onChanged();
        }
        if (!other.getAnimationName().isEmpty()) {
          animationName_ = other.animationName_;
          onChanged();
        }
        if (!other.getActionClassName().isEmpty()) {
          actionClassName_ = other.actionClassName_;
          onChanged();
        }
        if (other.getEntityOrientation() != 0) {
          setEntityOrientation(other.getEntityOrientation());
        }
        if (other.getFrameDuration() != 0F) {
          setFrameDuration(other.getFrameDuration());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.AnimationProto.AnimationPrototype parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.AnimationProto.AnimationPrototype) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object atlasName_ = "";
      /**
       * <code>string atlasName = 1;</code>
       */
      public java.lang.String getAtlasName() {
        java.lang.Object ref = atlasName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          atlasName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string atlasName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAtlasNameBytes() {
        java.lang.Object ref = atlasName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          atlasName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string atlasName = 1;</code>
       */
      public Builder setAtlasName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        atlasName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string atlasName = 1;</code>
       */
      public Builder clearAtlasName() {
        
        atlasName_ = getDefaultInstance().getAtlasName();
        onChanged();
        return this;
      }
      /**
       * <code>string atlasName = 1;</code>
       */
      public Builder setAtlasNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        atlasName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object animationName_ = "";
      /**
       * <code>string animationName = 2;</code>
       */
      public java.lang.String getAnimationName() {
        java.lang.Object ref = animationName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          animationName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string animationName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAnimationNameBytes() {
        java.lang.Object ref = animationName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          animationName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string animationName = 2;</code>
       */
      public Builder setAnimationName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        animationName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string animationName = 2;</code>
       */
      public Builder clearAnimationName() {
        
        animationName_ = getDefaultInstance().getAnimationName();
        onChanged();
        return this;
      }
      /**
       * <code>string animationName = 2;</code>
       */
      public Builder setAnimationNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        animationName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object actionClassName_ = "";
      /**
       * <code>string actionClassName = 3;</code>
       */
      public java.lang.String getActionClassName() {
        java.lang.Object ref = actionClassName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actionClassName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string actionClassName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getActionClassNameBytes() {
        java.lang.Object ref = actionClassName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actionClassName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actionClassName = 3;</code>
       */
      public Builder setActionClassName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        actionClassName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string actionClassName = 3;</code>
       */
      public Builder clearActionClassName() {
        
        actionClassName_ = getDefaultInstance().getActionClassName();
        onChanged();
        return this;
      }
      /**
       * <code>string actionClassName = 3;</code>
       */
      public Builder setActionClassNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        actionClassName_ = value;
        onChanged();
        return this;
      }

      private int entityOrientation_ ;
      /**
       * <code>int32 entityOrientation = 4;</code>
       */
      public int getEntityOrientation() {
        return entityOrientation_;
      }
      /**
       * <code>int32 entityOrientation = 4;</code>
       */
      public Builder setEntityOrientation(int value) {
        
        entityOrientation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 entityOrientation = 4;</code>
       */
      public Builder clearEntityOrientation() {
        
        entityOrientation_ = 0;
        onChanged();
        return this;
      }

      private float frameDuration_ ;
      /**
       * <code>float frameDuration = 5;</code>
       */
      public float getFrameDuration() {
        return frameDuration_;
      }
      /**
       * <code>float frameDuration = 5;</code>
       */
      public Builder setFrameDuration(float value) {
        
        frameDuration_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float frameDuration = 5;</code>
       */
      public Builder clearFrameDuration() {
        
        frameDuration_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AnimationPrototype)
    }

    // @@protoc_insertion_point(class_scope:AnimationPrototype)
    private static final com.reis.game.resource.prototype.AnimationProto.AnimationPrototype DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.AnimationProto.AnimationPrototype();
    }

    public static com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AnimationPrototype>
        PARSER = new com.google.protobuf.AbstractParser<AnimationPrototype>() {
      public AnimationPrototype parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new AnimationPrototype(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AnimationPrototype> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AnimationPrototype> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.AnimationProto.AnimationPrototype getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimationData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimationData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AnimationPrototype_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AnimationPrototype_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017animation.proto\"o\n\rAnimationData\022/\n\022an" +
      "imationPrototype\030\001 \003(\0132\023.AnimationProtot" +
      "ype\022-\n\020defaultAnimation\030\002 \001(\0132\023.Animatio" +
      "nPrototype\"\211\001\n\022AnimationPrototype\022\021\n\tatl" +
      "asName\030\001 \001(\t\022\025\n\ranimationName\030\002 \001(\t\022\027\n\017a" +
      "ctionClassName\030\003 \001(\t\022\031\n\021entityOrientatio" +
      "n\030\004 \001(\005\022\025\n\rframeDuration\030\005 \001(\002B2\n com.re" +
      "is.game.resource.prototypeB\016AnimationPro" +
      "tob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_AnimationData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AnimationData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimationData_descriptor,
        new java.lang.String[] { "AnimationPrototype", "DefaultAnimation", });
    internal_static_AnimationPrototype_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AnimationPrototype_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AnimationPrototype_descriptor,
        new java.lang.String[] { "AtlasName", "AnimationName", "ActionClassName", "EntityOrientation", "FrameDuration", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
