// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: entityType.proto

package com.reis.game.resource.prototype;

public final class EntityTypeProto {
  private EntityTypeProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntityDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>int32 row = 2;</code>
     */
    int getRow();

    /**
     * <code>int32 col = 3;</code>
     */
    int getCol();

    /**
     * <code>string templateName = 4;</code>
     */
    java.lang.String getTemplateName();
    /**
     * <code>string templateName = 4;</code>
     */
    com.google.protobuf.ByteString
        getTemplateNameBytes();

    /**
     * <pre>
     *int32 entityTypeId = 4;
     * </pre>
     *
     * <code>.AIData aiData = 5;</code>
     */
    boolean hasAiData();
    /**
     * <pre>
     *int32 entityTypeId = 4;
     * </pre>
     *
     * <code>.AIData aiData = 5;</code>
     */
    com.reis.game.resource.prototype.AI.AIData getAiData();
    /**
     * <pre>
     *int32 entityTypeId = 4;
     * </pre>
     *
     * <code>.AIData aiData = 5;</code>
     */
    com.reis.game.resource.prototype.AI.AIDataOrBuilder getAiDataOrBuilder();
  }
  /**
   * Protobuf type {@code EntityData}
   */
  public  static final class EntityData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EntityData)
      EntityDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityData.newBuilder() to construct.
    private EntityData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityData() {
      id_ = 0;
      row_ = 0;
      col_ = 0;
      templateName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              row_ = input.readInt32();
              break;
            }
            case 24: {

              col_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              templateName_ = s;
              break;
            }
            case 42: {
              com.reis.game.resource.prototype.AI.AIData.Builder subBuilder = null;
              if (aiData_ != null) {
                subBuilder = aiData_.toBuilder();
              }
              aiData_ = input.readMessage(com.reis.game.resource.prototype.AI.AIData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(aiData_);
                aiData_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.EntityTypeProto.EntityData.class, com.reis.game.resource.prototype.EntityTypeProto.EntityData.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ROW_FIELD_NUMBER = 2;
    private int row_;
    /**
     * <code>int32 row = 2;</code>
     */
    public int getRow() {
      return row_;
    }

    public static final int COL_FIELD_NUMBER = 3;
    private int col_;
    /**
     * <code>int32 col = 3;</code>
     */
    public int getCol() {
      return col_;
    }

    public static final int TEMPLATENAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object templateName_;
    /**
     * <code>string templateName = 4;</code>
     */
    public java.lang.String getTemplateName() {
      java.lang.Object ref = templateName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        templateName_ = s;
        return s;
      }
    }
    /**
     * <code>string templateName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTemplateNameBytes() {
      java.lang.Object ref = templateName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AIDATA_FIELD_NUMBER = 5;
    private com.reis.game.resource.prototype.AI.AIData aiData_;
    /**
     * <pre>
     *int32 entityTypeId = 4;
     * </pre>
     *
     * <code>.AIData aiData = 5;</code>
     */
    public boolean hasAiData() {
      return aiData_ != null;
    }
    /**
     * <pre>
     *int32 entityTypeId = 4;
     * </pre>
     *
     * <code>.AIData aiData = 5;</code>
     */
    public com.reis.game.resource.prototype.AI.AIData getAiData() {
      return aiData_ == null ? com.reis.game.resource.prototype.AI.AIData.getDefaultInstance() : aiData_;
    }
    /**
     * <pre>
     *int32 entityTypeId = 4;
     * </pre>
     *
     * <code>.AIData aiData = 5;</code>
     */
    public com.reis.game.resource.prototype.AI.AIDataOrBuilder getAiDataOrBuilder() {
      return getAiData();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (row_ != 0) {
        output.writeInt32(2, row_);
      }
      if (col_ != 0) {
        output.writeInt32(3, col_);
      }
      if (!getTemplateNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, templateName_);
      }
      if (aiData_ != null) {
        output.writeMessage(5, getAiData());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (row_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, row_);
      }
      if (col_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, col_);
      }
      if (!getTemplateNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, templateName_);
      }
      if (aiData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getAiData());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.EntityTypeProto.EntityData)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.EntityTypeProto.EntityData other = (com.reis.game.resource.prototype.EntityTypeProto.EntityData) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && (getRow()
          == other.getRow());
      result = result && (getCol()
          == other.getCol());
      result = result && getTemplateName()
          .equals(other.getTemplateName());
      result = result && (hasAiData() == other.hasAiData());
      if (hasAiData()) {
        result = result && getAiData()
            .equals(other.getAiData());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ROW_FIELD_NUMBER;
      hash = (53 * hash) + getRow();
      hash = (37 * hash) + COL_FIELD_NUMBER;
      hash = (53 * hash) + getCol();
      hash = (37 * hash) + TEMPLATENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTemplateName().hashCode();
      if (hasAiData()) {
        hash = (37 * hash) + AIDATA_FIELD_NUMBER;
        hash = (53 * hash) + getAiData().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.EntityTypeProto.EntityData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EntityData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityData)
        com.reis.game.resource.prototype.EntityTypeProto.EntityDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.EntityTypeProto.EntityData.class, com.reis.game.resource.prototype.EntityTypeProto.EntityData.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.EntityTypeProto.EntityData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        row_ = 0;

        col_ = 0;

        templateName_ = "";

        if (aiDataBuilder_ == null) {
          aiData_ = null;
        } else {
          aiData_ = null;
          aiDataBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityData_descriptor;
      }

      public com.reis.game.resource.prototype.EntityTypeProto.EntityData getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.EntityTypeProto.EntityData.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.EntityTypeProto.EntityData build() {
        com.reis.game.resource.prototype.EntityTypeProto.EntityData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.EntityTypeProto.EntityData buildPartial() {
        com.reis.game.resource.prototype.EntityTypeProto.EntityData result = new com.reis.game.resource.prototype.EntityTypeProto.EntityData(this);
        result.id_ = id_;
        result.row_ = row_;
        result.col_ = col_;
        result.templateName_ = templateName_;
        if (aiDataBuilder_ == null) {
          result.aiData_ = aiData_;
        } else {
          result.aiData_ = aiDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.EntityTypeProto.EntityData) {
          return mergeFrom((com.reis.game.resource.prototype.EntityTypeProto.EntityData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.EntityTypeProto.EntityData other) {
        if (other == com.reis.game.resource.prototype.EntityTypeProto.EntityData.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getRow() != 0) {
          setRow(other.getRow());
        }
        if (other.getCol() != 0) {
          setCol(other.getCol());
        }
        if (!other.getTemplateName().isEmpty()) {
          templateName_ = other.templateName_;
          onChanged();
        }
        if (other.hasAiData()) {
          mergeAiData(other.getAiData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.EntityTypeProto.EntityData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.EntityTypeProto.EntityData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int row_ ;
      /**
       * <code>int32 row = 2;</code>
       */
      public int getRow() {
        return row_;
      }
      /**
       * <code>int32 row = 2;</code>
       */
      public Builder setRow(int value) {
        
        row_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 row = 2;</code>
       */
      public Builder clearRow() {
        
        row_ = 0;
        onChanged();
        return this;
      }

      private int col_ ;
      /**
       * <code>int32 col = 3;</code>
       */
      public int getCol() {
        return col_;
      }
      /**
       * <code>int32 col = 3;</code>
       */
      public Builder setCol(int value) {
        
        col_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 col = 3;</code>
       */
      public Builder clearCol() {
        
        col_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object templateName_ = "";
      /**
       * <code>string templateName = 4;</code>
       */
      public java.lang.String getTemplateName() {
        java.lang.Object ref = templateName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          templateName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string templateName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTemplateNameBytes() {
        java.lang.Object ref = templateName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          templateName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string templateName = 4;</code>
       */
      public Builder setTemplateName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        templateName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string templateName = 4;</code>
       */
      public Builder clearTemplateName() {
        
        templateName_ = getDefaultInstance().getTemplateName();
        onChanged();
        return this;
      }
      /**
       * <code>string templateName = 4;</code>
       */
      public Builder setTemplateNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        templateName_ = value;
        onChanged();
        return this;
      }

      private com.reis.game.resource.prototype.AI.AIData aiData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.resource.prototype.AI.AIData, com.reis.game.resource.prototype.AI.AIData.Builder, com.reis.game.resource.prototype.AI.AIDataOrBuilder> aiDataBuilder_;
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public boolean hasAiData() {
        return aiDataBuilder_ != null || aiData_ != null;
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public com.reis.game.resource.prototype.AI.AIData getAiData() {
        if (aiDataBuilder_ == null) {
          return aiData_ == null ? com.reis.game.resource.prototype.AI.AIData.getDefaultInstance() : aiData_;
        } else {
          return aiDataBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public Builder setAiData(com.reis.game.resource.prototype.AI.AIData value) {
        if (aiDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          aiData_ = value;
          onChanged();
        } else {
          aiDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public Builder setAiData(
          com.reis.game.resource.prototype.AI.AIData.Builder builderForValue) {
        if (aiDataBuilder_ == null) {
          aiData_ = builderForValue.build();
          onChanged();
        } else {
          aiDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public Builder mergeAiData(com.reis.game.resource.prototype.AI.AIData value) {
        if (aiDataBuilder_ == null) {
          if (aiData_ != null) {
            aiData_ =
              com.reis.game.resource.prototype.AI.AIData.newBuilder(aiData_).mergeFrom(value).buildPartial();
          } else {
            aiData_ = value;
          }
          onChanged();
        } else {
          aiDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public Builder clearAiData() {
        if (aiDataBuilder_ == null) {
          aiData_ = null;
          onChanged();
        } else {
          aiData_ = null;
          aiDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public com.reis.game.resource.prototype.AI.AIData.Builder getAiDataBuilder() {
        
        onChanged();
        return getAiDataFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      public com.reis.game.resource.prototype.AI.AIDataOrBuilder getAiDataOrBuilder() {
        if (aiDataBuilder_ != null) {
          return aiDataBuilder_.getMessageOrBuilder();
        } else {
          return aiData_ == null ?
              com.reis.game.resource.prototype.AI.AIData.getDefaultInstance() : aiData_;
        }
      }
      /**
       * <pre>
       *int32 entityTypeId = 4;
       * </pre>
       *
       * <code>.AIData aiData = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.reis.game.resource.prototype.AI.AIData, com.reis.game.resource.prototype.AI.AIData.Builder, com.reis.game.resource.prototype.AI.AIDataOrBuilder> 
          getAiDataFieldBuilder() {
        if (aiDataBuilder_ == null) {
          aiDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.reis.game.resource.prototype.AI.AIData, com.reis.game.resource.prototype.AI.AIData.Builder, com.reis.game.resource.prototype.AI.AIDataOrBuilder>(
                  getAiData(),
                  getParentForChildren(),
                  isClean());
          aiData_ = null;
        }
        return aiDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EntityData)
    }

    // @@protoc_insertion_point(class_scope:EntityData)
    private static final com.reis.game.resource.prototype.EntityTypeProto.EntityData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.EntityTypeProto.EntityData();
    }

    public static com.reis.game.resource.prototype.EntityTypeProto.EntityData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityData>
        PARSER = new com.google.protobuf.AbstractParser<EntityData>() {
      public EntityData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EntityData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntityData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.EntityTypeProto.EntityData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EntityClassDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:EntityClassData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */
    int getEntityTypeForIdCount();
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */
    boolean containsEntityTypeForId(
        int key);
    /**
     * Use {@link #getEntityTypeForIdMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.String>
    getEntityTypeForId();
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.String>
    getEntityTypeForIdMap();
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */

    java.lang.String getEntityTypeForIdOrDefault(
        int key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */

    java.lang.String getEntityTypeForIdOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code EntityClassData}
   */
  public  static final class EntityClassData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:EntityClassData)
      EntityClassDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EntityClassData.newBuilder() to construct.
    private EntityClassData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EntityClassData() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EntityClassData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                entityTypeForId_ = com.google.protobuf.MapField.newMapField(
                    EntityTypeForIdDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
              entityTypeForId__ = input.readMessage(
                  EntityTypeForIdDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              entityTypeForId_.getMutableMap().put(
                  entityTypeForId__.getKey(), entityTypeForId__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityClassData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetEntityTypeForId();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityClassData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.EntityTypeProto.EntityClassData.class, com.reis.game.resource.prototype.EntityTypeProto.EntityClassData.Builder.class);
    }

    public static final int ENTITYTYPEFORID_FIELD_NUMBER = 1;
    private static final class EntityTypeForIdDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.String>newDefaultInstance(
                  com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityClassData_EntityTypeForIdEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.String> entityTypeForId_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
    internalGetEntityTypeForId() {
      if (entityTypeForId_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            EntityTypeForIdDefaultEntryHolder.defaultEntry);
      }
      return entityTypeForId_;
    }

    public int getEntityTypeForIdCount() {
      return internalGetEntityTypeForId().getMap().size();
    }
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */

    public boolean containsEntityTypeForId(
        int key) {
      
      return internalGetEntityTypeForId().getMap().containsKey(key);
    }
    /**
     * Use {@link #getEntityTypeForIdMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.String> getEntityTypeForId() {
      return getEntityTypeForIdMap();
    }
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.String> getEntityTypeForIdMap() {
      return internalGetEntityTypeForId().getMap();
    }
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */

    public java.lang.String getEntityTypeForIdOrDefault(
        int key,
        java.lang.String defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetEntityTypeForId().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
     */

    public java.lang.String getEntityTypeForIdOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.String> map =
          internalGetEntityTypeForId().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetEntityTypeForId(),
          EntityTypeForIdDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, java.lang.String> entry
           : internalGetEntityTypeForId().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.String>
        entityTypeForId__ = EntityTypeForIdDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, entityTypeForId__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.EntityTypeProto.EntityClassData)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.EntityTypeProto.EntityClassData other = (com.reis.game.resource.prototype.EntityTypeProto.EntityClassData) obj;

      boolean result = true;
      result = result && internalGetEntityTypeForId().equals(
          other.internalGetEntityTypeForId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetEntityTypeForId().getMap().isEmpty()) {
        hash = (37 * hash) + ENTITYTYPEFORID_FIELD_NUMBER;
        hash = (53 * hash) + internalGetEntityTypeForId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.EntityTypeProto.EntityClassData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code EntityClassData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:EntityClassData)
        com.reis.game.resource.prototype.EntityTypeProto.EntityClassDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityClassData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetEntityTypeForId();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableEntityTypeForId();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityClassData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.EntityTypeProto.EntityClassData.class, com.reis.game.resource.prototype.EntityTypeProto.EntityClassData.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.EntityTypeProto.EntityClassData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableEntityTypeForId().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.EntityTypeProto.internal_static_EntityClassData_descriptor;
      }

      public com.reis.game.resource.prototype.EntityTypeProto.EntityClassData getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.EntityTypeProto.EntityClassData.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.EntityTypeProto.EntityClassData build() {
        com.reis.game.resource.prototype.EntityTypeProto.EntityClassData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.EntityTypeProto.EntityClassData buildPartial() {
        com.reis.game.resource.prototype.EntityTypeProto.EntityClassData result = new com.reis.game.resource.prototype.EntityTypeProto.EntityClassData(this);
        int from_bitField0_ = bitField0_;
        result.entityTypeForId_ = internalGetEntityTypeForId();
        result.entityTypeForId_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.EntityTypeProto.EntityClassData) {
          return mergeFrom((com.reis.game.resource.prototype.EntityTypeProto.EntityClassData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.EntityTypeProto.EntityClassData other) {
        if (other == com.reis.game.resource.prototype.EntityTypeProto.EntityClassData.getDefaultInstance()) return this;
        internalGetMutableEntityTypeForId().mergeFrom(
            other.internalGetEntityTypeForId());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.EntityTypeProto.EntityClassData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.EntityTypeProto.EntityClassData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.String> entityTypeForId_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetEntityTypeForId() {
        if (entityTypeForId_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              EntityTypeForIdDefaultEntryHolder.defaultEntry);
        }
        return entityTypeForId_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.String>
      internalGetMutableEntityTypeForId() {
        onChanged();;
        if (entityTypeForId_ == null) {
          entityTypeForId_ = com.google.protobuf.MapField.newMapField(
              EntityTypeForIdDefaultEntryHolder.defaultEntry);
        }
        if (!entityTypeForId_.isMutable()) {
          entityTypeForId_ = entityTypeForId_.copy();
        }
        return entityTypeForId_;
      }

      public int getEntityTypeForIdCount() {
        return internalGetEntityTypeForId().getMap().size();
      }
      /**
       * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
       */

      public boolean containsEntityTypeForId(
          int key) {
        
        return internalGetEntityTypeForId().getMap().containsKey(key);
      }
      /**
       * Use {@link #getEntityTypeForIdMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String> getEntityTypeForId() {
        return getEntityTypeForIdMap();
      }
      /**
       * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.String> getEntityTypeForIdMap() {
        return internalGetEntityTypeForId().getMap();
      }
      /**
       * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
       */

      public java.lang.String getEntityTypeForIdOrDefault(
          int key,
          java.lang.String defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetEntityTypeForId().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
       */

      public java.lang.String getEntityTypeForIdOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.String> map =
            internalGetEntityTypeForId().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearEntityTypeForId() {
        internalGetMutableEntityTypeForId().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
       */

      public Builder removeEntityTypeForId(
          int key) {
        
        internalGetMutableEntityTypeForId().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.String>
      getMutableEntityTypeForId() {
        return internalGetMutableEntityTypeForId().getMutableMap();
      }
      /**
       * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
       */
      public Builder putEntityTypeForId(
          int key,
          java.lang.String value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableEntityTypeForId().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, string&gt; entityTypeForId = 1;</code>
       */

      public Builder putAllEntityTypeForId(
          java.util.Map<java.lang.Integer, java.lang.String> values) {
        internalGetMutableEntityTypeForId().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:EntityClassData)
    }

    // @@protoc_insertion_point(class_scope:EntityClassData)
    private static final com.reis.game.resource.prototype.EntityTypeProto.EntityClassData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.EntityTypeProto.EntityClassData();
    }

    public static com.reis.game.resource.prototype.EntityTypeProto.EntityClassData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EntityClassData>
        PARSER = new com.google.protobuf.AbstractParser<EntityClassData>() {
      public EntityClassData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EntityClassData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EntityClassData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EntityClassData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.EntityTypeProto.EntityClassData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityClassData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityClassData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EntityClassData_EntityTypeForIdEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EntityClassData_EntityTypeForIdEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020entityType.proto\032\010ai.proto\"a\n\nEntityDa" +
      "ta\022\n\n\002id\030\001 \001(\005\022\013\n\003row\030\002 \001(\005\022\013\n\003col\030\003 \001(\005" +
      "\022\024\n\014templateName\030\004 \001(\t\022\027\n\006aiData\030\005 \001(\0132\007" +
      ".AIData\"\211\001\n\017EntityClassData\022>\n\017entityTyp" +
      "eForId\030\001 \003(\0132%.EntityClassData.EntityTyp" +
      "eForIdEntry\0326\n\024EntityTypeForIdEntry\022\013\n\003k" +
      "ey\030\001 \001(\005\022\r\n\005value\030\002 \001(\t:\0028\001B3\n com.reis." +
      "game.resource.prototypeB\017EntityTypeProto" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.reis.game.resource.prototype.AI.getDescriptor(),
        }, assigner);
    internal_static_EntityData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EntityData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityData_descriptor,
        new java.lang.String[] { "Id", "Row", "Col", "TemplateName", "AiData", });
    internal_static_EntityClassData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EntityClassData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityClassData_descriptor,
        new java.lang.String[] { "EntityTypeForId", });
    internal_static_EntityClassData_EntityTypeForIdEntry_descriptor =
      internal_static_EntityClassData_descriptor.getNestedTypes().get(0);
    internal_static_EntityClassData_EntityTypeForIdEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EntityClassData_EntityTypeForIdEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    com.reis.game.resource.prototype.AI.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
