// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: questLog.proto

package com.reis.game.resource.prototype;

public final class QuestLogProto {
  private QuestLogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuestLogDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QuestLogData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */
    int getQuestLogCount();
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */
    boolean containsQuestLog(
        int key);
    /**
     * Use {@link #getQuestLogMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
    getQuestLog();
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */
    java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
    getQuestLogMap();
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */

    com.reis.game.resource.prototype.QuestLogProto.QuestStepData getQuestLogOrDefault(
        int key,
        com.reis.game.resource.prototype.QuestLogProto.QuestStepData defaultValue);
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */

    com.reis.game.resource.prototype.QuestLogProto.QuestStepData getQuestLogOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code QuestLogData}
   */
  public  static final class QuestLogData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QuestLogData)
      QuestLogDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuestLogData.newBuilder() to construct.
    private QuestLogData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestLogData() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuestLogData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                questLog_ = com.google.protobuf.MapField.newMapField(
                    QuestLogDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
              questLog__ = input.readMessage(
                  QuestLogDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              questLog_.getMutableMap().put(
                  questLog__.getKey(), questLog__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestLogData_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetQuestLog();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestLogData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.QuestLogProto.QuestLogData.class, com.reis.game.resource.prototype.QuestLogProto.QuestLogData.Builder.class);
    }

    public static final int QUESTLOG_FIELD_NUMBER = 1;
    private static final class QuestLogDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>newDefaultInstance(
                  com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestLogData_QuestLogEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.reis.game.resource.prototype.QuestLogProto.QuestStepData.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> questLog_;
    private com.google.protobuf.MapField<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
    internalGetQuestLog() {
      if (questLog_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            QuestLogDefaultEntryHolder.defaultEntry);
      }
      return questLog_;
    }

    public int getQuestLogCount() {
      return internalGetQuestLog().getMap().size();
    }
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */

    public boolean containsQuestLog(
        int key) {
      
      return internalGetQuestLog().getMap().containsKey(key);
    }
    /**
     * Use {@link #getQuestLogMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> getQuestLog() {
      return getQuestLogMap();
    }
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */

    public java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> getQuestLogMap() {
      return internalGetQuestLog().getMap();
    }
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */

    public com.reis.game.resource.prototype.QuestLogProto.QuestStepData getQuestLogOrDefault(
        int key,
        com.reis.game.resource.prototype.QuestLogProto.QuestStepData defaultValue) {
      
      java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> map =
          internalGetQuestLog().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
     */

    public com.reis.game.resource.prototype.QuestLogProto.QuestStepData getQuestLogOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> map =
          internalGetQuestLog().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetQuestLog(),
          QuestLogDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> entry
           : internalGetQuestLog().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
        questLog__ = QuestLogDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, questLog__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.QuestLogProto.QuestLogData)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.QuestLogProto.QuestLogData other = (com.reis.game.resource.prototype.QuestLogProto.QuestLogData) obj;

      boolean result = true;
      result = result && internalGetQuestLog().equals(
          other.internalGetQuestLog());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetQuestLog().getMap().isEmpty()) {
        hash = (37 * hash) + QUESTLOG_FIELD_NUMBER;
        hash = (53 * hash) + internalGetQuestLog().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.QuestLogProto.QuestLogData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QuestLogData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QuestLogData)
        com.reis.game.resource.prototype.QuestLogProto.QuestLogDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestLogData_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetQuestLog();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableQuestLog();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestLogData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.QuestLogProto.QuestLogData.class, com.reis.game.resource.prototype.QuestLogProto.QuestLogData.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.QuestLogProto.QuestLogData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableQuestLog().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestLogData_descriptor;
      }

      public com.reis.game.resource.prototype.QuestLogProto.QuestLogData getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.QuestLogProto.QuestLogData.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.QuestLogProto.QuestLogData build() {
        com.reis.game.resource.prototype.QuestLogProto.QuestLogData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.QuestLogProto.QuestLogData buildPartial() {
        com.reis.game.resource.prototype.QuestLogProto.QuestLogData result = new com.reis.game.resource.prototype.QuestLogProto.QuestLogData(this);
        int from_bitField0_ = bitField0_;
        result.questLog_ = internalGetQuestLog();
        result.questLog_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.QuestLogProto.QuestLogData) {
          return mergeFrom((com.reis.game.resource.prototype.QuestLogProto.QuestLogData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.QuestLogProto.QuestLogData other) {
        if (other == com.reis.game.resource.prototype.QuestLogProto.QuestLogData.getDefaultInstance()) return this;
        internalGetMutableQuestLog().mergeFrom(
            other.internalGetQuestLog());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.QuestLogProto.QuestLogData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.QuestLogProto.QuestLogData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> questLog_;
      private com.google.protobuf.MapField<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
      internalGetQuestLog() {
        if (questLog_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              QuestLogDefaultEntryHolder.defaultEntry);
        }
        return questLog_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
      internalGetMutableQuestLog() {
        onChanged();;
        if (questLog_ == null) {
          questLog_ = com.google.protobuf.MapField.newMapField(
              QuestLogDefaultEntryHolder.defaultEntry);
        }
        if (!questLog_.isMutable()) {
          questLog_ = questLog_.copy();
        }
        return questLog_;
      }

      public int getQuestLogCount() {
        return internalGetQuestLog().getMap().size();
      }
      /**
       * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
       */

      public boolean containsQuestLog(
          int key) {
        
        return internalGetQuestLog().getMap().containsKey(key);
      }
      /**
       * Use {@link #getQuestLogMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> getQuestLog() {
        return getQuestLogMap();
      }
      /**
       * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
       */

      public java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> getQuestLogMap() {
        return internalGetQuestLog().getMap();
      }
      /**
       * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
       */

      public com.reis.game.resource.prototype.QuestLogProto.QuestStepData getQuestLogOrDefault(
          int key,
          com.reis.game.resource.prototype.QuestLogProto.QuestStepData defaultValue) {
        
        java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> map =
            internalGetQuestLog().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
       */

      public com.reis.game.resource.prototype.QuestLogProto.QuestStepData getQuestLogOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> map =
            internalGetQuestLog().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearQuestLog() {
        internalGetMutableQuestLog().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
       */

      public Builder removeQuestLog(
          int key) {
        
        internalGetMutableQuestLog().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData>
      getMutableQuestLog() {
        return internalGetMutableQuestLog().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
       */
      public Builder putQuestLog(
          int key,
          com.reis.game.resource.prototype.QuestLogProto.QuestStepData value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableQuestLog().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, .QuestStepData&gt; questLog = 1;</code>
       */

      public Builder putAllQuestLog(
          java.util.Map<java.lang.Integer, com.reis.game.resource.prototype.QuestLogProto.QuestStepData> values) {
        internalGetMutableQuestLog().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QuestLogData)
    }

    // @@protoc_insertion_point(class_scope:QuestLogData)
    private static final com.reis.game.resource.prototype.QuestLogProto.QuestLogData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.QuestLogProto.QuestLogData();
    }

    public static com.reis.game.resource.prototype.QuestLogProto.QuestLogData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuestLogData>
        PARSER = new com.google.protobuf.AbstractParser<QuestLogData>() {
      public QuestLogData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QuestLogData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestLogData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestLogData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.QuestLogProto.QuestLogData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuestStepDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QuestStepData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    java.util.List<com.reis.game.resource.prototype.RequirementProto.RequirementData> 
        getRequirementsList();
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    com.reis.game.resource.prototype.RequirementProto.RequirementData getRequirements(int index);
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    int getRequirementsCount();
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    java.util.List<? extends com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder> 
        getRequirementsOrBuilderList();
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder getRequirementsOrBuilder(
        int index);

    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    java.util.List<com.reis.game.resource.prototype.ReactionProto.ReactionData> 
        getReactionsList();
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    com.reis.game.resource.prototype.ReactionProto.ReactionData getReactions(int index);
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    int getReactionsCount();
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    java.util.List<? extends com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder> 
        getReactionsOrBuilderList();
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder getReactionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code QuestStepData}
   */
  public  static final class QuestStepData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QuestStepData)
      QuestStepDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuestStepData.newBuilder() to construct.
    private QuestStepData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestStepData() {
      requirements_ = java.util.Collections.emptyList();
      reactions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuestStepData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                requirements_ = new java.util.ArrayList<com.reis.game.resource.prototype.RequirementProto.RequirementData>();
                mutable_bitField0_ |= 0x00000001;
              }
              requirements_.add(
                  input.readMessage(com.reis.game.resource.prototype.RequirementProto.RequirementData.parser(), extensionRegistry));
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                reactions_ = new java.util.ArrayList<com.reis.game.resource.prototype.ReactionProto.ReactionData>();
                mutable_bitField0_ |= 0x00000002;
              }
              reactions_.add(
                  input.readMessage(com.reis.game.resource.prototype.ReactionProto.ReactionData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          requirements_ = java.util.Collections.unmodifiableList(requirements_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          reactions_ = java.util.Collections.unmodifiableList(reactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestStepData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestStepData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.QuestLogProto.QuestStepData.class, com.reis.game.resource.prototype.QuestLogProto.QuestStepData.Builder.class);
    }

    public static final int REQUIREMENTS_FIELD_NUMBER = 1;
    private java.util.List<com.reis.game.resource.prototype.RequirementProto.RequirementData> requirements_;
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    public java.util.List<com.reis.game.resource.prototype.RequirementProto.RequirementData> getRequirementsList() {
      return requirements_;
    }
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    public java.util.List<? extends com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder> 
        getRequirementsOrBuilderList() {
      return requirements_;
    }
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    public int getRequirementsCount() {
      return requirements_.size();
    }
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    public com.reis.game.resource.prototype.RequirementProto.RequirementData getRequirements(int index) {
      return requirements_.get(index);
    }
    /**
     * <code>repeated .RequirementData requirements = 1;</code>
     */
    public com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder getRequirementsOrBuilder(
        int index) {
      return requirements_.get(index);
    }

    public static final int REACTIONS_FIELD_NUMBER = 2;
    private java.util.List<com.reis.game.resource.prototype.ReactionProto.ReactionData> reactions_;
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    public java.util.List<com.reis.game.resource.prototype.ReactionProto.ReactionData> getReactionsList() {
      return reactions_;
    }
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    public java.util.List<? extends com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder> 
        getReactionsOrBuilderList() {
      return reactions_;
    }
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    public int getReactionsCount() {
      return reactions_.size();
    }
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    public com.reis.game.resource.prototype.ReactionProto.ReactionData getReactions(int index) {
      return reactions_.get(index);
    }
    /**
     * <code>repeated .ReactionData reactions = 2;</code>
     */
    public com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder getReactionsOrBuilder(
        int index) {
      return reactions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < requirements_.size(); i++) {
        output.writeMessage(1, requirements_.get(i));
      }
      for (int i = 0; i < reactions_.size(); i++) {
        output.writeMessage(2, reactions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < requirements_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, requirements_.get(i));
      }
      for (int i = 0; i < reactions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, reactions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.QuestLogProto.QuestStepData)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.QuestLogProto.QuestStepData other = (com.reis.game.resource.prototype.QuestLogProto.QuestStepData) obj;

      boolean result = true;
      result = result && getRequirementsList()
          .equals(other.getRequirementsList());
      result = result && getReactionsList()
          .equals(other.getReactionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getRequirementsCount() > 0) {
        hash = (37 * hash) + REQUIREMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getRequirementsList().hashCode();
      }
      if (getReactionsCount() > 0) {
        hash = (37 * hash) + REACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getReactionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.QuestLogProto.QuestStepData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QuestStepData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QuestStepData)
        com.reis.game.resource.prototype.QuestLogProto.QuestStepDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestStepData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestStepData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.QuestLogProto.QuestStepData.class, com.reis.game.resource.prototype.QuestLogProto.QuestStepData.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.QuestLogProto.QuestStepData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRequirementsFieldBuilder();
          getReactionsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (requirementsBuilder_ == null) {
          requirements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          requirementsBuilder_.clear();
        }
        if (reactionsBuilder_ == null) {
          reactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          reactionsBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.QuestLogProto.internal_static_QuestStepData_descriptor;
      }

      public com.reis.game.resource.prototype.QuestLogProto.QuestStepData getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.QuestLogProto.QuestStepData.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.QuestLogProto.QuestStepData build() {
        com.reis.game.resource.prototype.QuestLogProto.QuestStepData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.QuestLogProto.QuestStepData buildPartial() {
        com.reis.game.resource.prototype.QuestLogProto.QuestStepData result = new com.reis.game.resource.prototype.QuestLogProto.QuestStepData(this);
        int from_bitField0_ = bitField0_;
        if (requirementsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            requirements_ = java.util.Collections.unmodifiableList(requirements_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.requirements_ = requirements_;
        } else {
          result.requirements_ = requirementsBuilder_.build();
        }
        if (reactionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            reactions_ = java.util.Collections.unmodifiableList(reactions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.reactions_ = reactions_;
        } else {
          result.reactions_ = reactionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.QuestLogProto.QuestStepData) {
          return mergeFrom((com.reis.game.resource.prototype.QuestLogProto.QuestStepData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.QuestLogProto.QuestStepData other) {
        if (other == com.reis.game.resource.prototype.QuestLogProto.QuestStepData.getDefaultInstance()) return this;
        if (requirementsBuilder_ == null) {
          if (!other.requirements_.isEmpty()) {
            if (requirements_.isEmpty()) {
              requirements_ = other.requirements_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRequirementsIsMutable();
              requirements_.addAll(other.requirements_);
            }
            onChanged();
          }
        } else {
          if (!other.requirements_.isEmpty()) {
            if (requirementsBuilder_.isEmpty()) {
              requirementsBuilder_.dispose();
              requirementsBuilder_ = null;
              requirements_ = other.requirements_;
              bitField0_ = (bitField0_ & ~0x00000001);
              requirementsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRequirementsFieldBuilder() : null;
            } else {
              requirementsBuilder_.addAllMessages(other.requirements_);
            }
          }
        }
        if (reactionsBuilder_ == null) {
          if (!other.reactions_.isEmpty()) {
            if (reactions_.isEmpty()) {
              reactions_ = other.reactions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureReactionsIsMutable();
              reactions_.addAll(other.reactions_);
            }
            onChanged();
          }
        } else {
          if (!other.reactions_.isEmpty()) {
            if (reactionsBuilder_.isEmpty()) {
              reactionsBuilder_.dispose();
              reactionsBuilder_ = null;
              reactions_ = other.reactions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              reactionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getReactionsFieldBuilder() : null;
            } else {
              reactionsBuilder_.addAllMessages(other.reactions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.QuestLogProto.QuestStepData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.QuestLogProto.QuestStepData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.reis.game.resource.prototype.RequirementProto.RequirementData> requirements_ =
        java.util.Collections.emptyList();
      private void ensureRequirementsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          requirements_ = new java.util.ArrayList<com.reis.game.resource.prototype.RequirementProto.RequirementData>(requirements_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.RequirementProto.RequirementData, com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder, com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder> requirementsBuilder_;

      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.RequirementProto.RequirementData> getRequirementsList() {
        if (requirementsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(requirements_);
        } else {
          return requirementsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public int getRequirementsCount() {
        if (requirementsBuilder_ == null) {
          return requirements_.size();
        } else {
          return requirementsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public com.reis.game.resource.prototype.RequirementProto.RequirementData getRequirements(int index) {
        if (requirementsBuilder_ == null) {
          return requirements_.get(index);
        } else {
          return requirementsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder setRequirements(
          int index, com.reis.game.resource.prototype.RequirementProto.RequirementData value) {
        if (requirementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequirementsIsMutable();
          requirements_.set(index, value);
          onChanged();
        } else {
          requirementsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder setRequirements(
          int index, com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder builderForValue) {
        if (requirementsBuilder_ == null) {
          ensureRequirementsIsMutable();
          requirements_.set(index, builderForValue.build());
          onChanged();
        } else {
          requirementsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder addRequirements(com.reis.game.resource.prototype.RequirementProto.RequirementData value) {
        if (requirementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequirementsIsMutable();
          requirements_.add(value);
          onChanged();
        } else {
          requirementsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder addRequirements(
          int index, com.reis.game.resource.prototype.RequirementProto.RequirementData value) {
        if (requirementsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRequirementsIsMutable();
          requirements_.add(index, value);
          onChanged();
        } else {
          requirementsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder addRequirements(
          com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder builderForValue) {
        if (requirementsBuilder_ == null) {
          ensureRequirementsIsMutable();
          requirements_.add(builderForValue.build());
          onChanged();
        } else {
          requirementsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder addRequirements(
          int index, com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder builderForValue) {
        if (requirementsBuilder_ == null) {
          ensureRequirementsIsMutable();
          requirements_.add(index, builderForValue.build());
          onChanged();
        } else {
          requirementsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder addAllRequirements(
          java.lang.Iterable<? extends com.reis.game.resource.prototype.RequirementProto.RequirementData> values) {
        if (requirementsBuilder_ == null) {
          ensureRequirementsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, requirements_);
          onChanged();
        } else {
          requirementsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder clearRequirements() {
        if (requirementsBuilder_ == null) {
          requirements_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          requirementsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public Builder removeRequirements(int index) {
        if (requirementsBuilder_ == null) {
          ensureRequirementsIsMutable();
          requirements_.remove(index);
          onChanged();
        } else {
          requirementsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder getRequirementsBuilder(
          int index) {
        return getRequirementsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder getRequirementsOrBuilder(
          int index) {
        if (requirementsBuilder_ == null) {
          return requirements_.get(index);  } else {
          return requirementsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public java.util.List<? extends com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder> 
           getRequirementsOrBuilderList() {
        if (requirementsBuilder_ != null) {
          return requirementsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(requirements_);
        }
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder addRequirementsBuilder() {
        return getRequirementsFieldBuilder().addBuilder(
            com.reis.game.resource.prototype.RequirementProto.RequirementData.getDefaultInstance());
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder addRequirementsBuilder(
          int index) {
        return getRequirementsFieldBuilder().addBuilder(
            index, com.reis.game.resource.prototype.RequirementProto.RequirementData.getDefaultInstance());
      }
      /**
       * <code>repeated .RequirementData requirements = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder> 
           getRequirementsBuilderList() {
        return getRequirementsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.RequirementProto.RequirementData, com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder, com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder> 
          getRequirementsFieldBuilder() {
        if (requirementsBuilder_ == null) {
          requirementsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.reis.game.resource.prototype.RequirementProto.RequirementData, com.reis.game.resource.prototype.RequirementProto.RequirementData.Builder, com.reis.game.resource.prototype.RequirementProto.RequirementDataOrBuilder>(
                  requirements_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          requirements_ = null;
        }
        return requirementsBuilder_;
      }

      private java.util.List<com.reis.game.resource.prototype.ReactionProto.ReactionData> reactions_ =
        java.util.Collections.emptyList();
      private void ensureReactionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          reactions_ = new java.util.ArrayList<com.reis.game.resource.prototype.ReactionProto.ReactionData>(reactions_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.ReactionProto.ReactionData, com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder, com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder> reactionsBuilder_;

      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.ReactionProto.ReactionData> getReactionsList() {
        if (reactionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(reactions_);
        } else {
          return reactionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public int getReactionsCount() {
        if (reactionsBuilder_ == null) {
          return reactions_.size();
        } else {
          return reactionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public com.reis.game.resource.prototype.ReactionProto.ReactionData getReactions(int index) {
        if (reactionsBuilder_ == null) {
          return reactions_.get(index);
        } else {
          return reactionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder setReactions(
          int index, com.reis.game.resource.prototype.ReactionProto.ReactionData value) {
        if (reactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReactionsIsMutable();
          reactions_.set(index, value);
          onChanged();
        } else {
          reactionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder setReactions(
          int index, com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder builderForValue) {
        if (reactionsBuilder_ == null) {
          ensureReactionsIsMutable();
          reactions_.set(index, builderForValue.build());
          onChanged();
        } else {
          reactionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder addReactions(com.reis.game.resource.prototype.ReactionProto.ReactionData value) {
        if (reactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReactionsIsMutable();
          reactions_.add(value);
          onChanged();
        } else {
          reactionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder addReactions(
          int index, com.reis.game.resource.prototype.ReactionProto.ReactionData value) {
        if (reactionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureReactionsIsMutable();
          reactions_.add(index, value);
          onChanged();
        } else {
          reactionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder addReactions(
          com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder builderForValue) {
        if (reactionsBuilder_ == null) {
          ensureReactionsIsMutable();
          reactions_.add(builderForValue.build());
          onChanged();
        } else {
          reactionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder addReactions(
          int index, com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder builderForValue) {
        if (reactionsBuilder_ == null) {
          ensureReactionsIsMutable();
          reactions_.add(index, builderForValue.build());
          onChanged();
        } else {
          reactionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder addAllReactions(
          java.lang.Iterable<? extends com.reis.game.resource.prototype.ReactionProto.ReactionData> values) {
        if (reactionsBuilder_ == null) {
          ensureReactionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, reactions_);
          onChanged();
        } else {
          reactionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder clearReactions() {
        if (reactionsBuilder_ == null) {
          reactions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          reactionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public Builder removeReactions(int index) {
        if (reactionsBuilder_ == null) {
          ensureReactionsIsMutable();
          reactions_.remove(index);
          onChanged();
        } else {
          reactionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder getReactionsBuilder(
          int index) {
        return getReactionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder getReactionsOrBuilder(
          int index) {
        if (reactionsBuilder_ == null) {
          return reactions_.get(index);  } else {
          return reactionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public java.util.List<? extends com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder> 
           getReactionsOrBuilderList() {
        if (reactionsBuilder_ != null) {
          return reactionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(reactions_);
        }
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder addReactionsBuilder() {
        return getReactionsFieldBuilder().addBuilder(
            com.reis.game.resource.prototype.ReactionProto.ReactionData.getDefaultInstance());
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder addReactionsBuilder(
          int index) {
        return getReactionsFieldBuilder().addBuilder(
            index, com.reis.game.resource.prototype.ReactionProto.ReactionData.getDefaultInstance());
      }
      /**
       * <code>repeated .ReactionData reactions = 2;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder> 
           getReactionsBuilderList() {
        return getReactionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.ReactionProto.ReactionData, com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder, com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder> 
          getReactionsFieldBuilder() {
        if (reactionsBuilder_ == null) {
          reactionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.reis.game.resource.prototype.ReactionProto.ReactionData, com.reis.game.resource.prototype.ReactionProto.ReactionData.Builder, com.reis.game.resource.prototype.ReactionProto.ReactionDataOrBuilder>(
                  reactions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          reactions_ = null;
        }
        return reactionsBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QuestStepData)
    }

    // @@protoc_insertion_point(class_scope:QuestStepData)
    private static final com.reis.game.resource.prototype.QuestLogProto.QuestStepData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.QuestLogProto.QuestStepData();
    }

    public static com.reis.game.resource.prototype.QuestLogProto.QuestStepData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuestStepData>
        PARSER = new com.google.protobuf.AbstractParser<QuestStepData>() {
      public QuestStepData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QuestStepData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestStepData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestStepData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.QuestLogProto.QuestStepData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestLogData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestLogData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestLogData_QuestLogEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestLogData_QuestLogEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestStepData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestStepData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016questLog.proto\032\021requirement.proto\032\016rea" +
      "ction.proto\"~\n\014QuestLogData\022-\n\010questLog\030" +
      "\001 \003(\0132\033.QuestLogData.QuestLogEntry\032?\n\rQu" +
      "estLogEntry\022\013\n\003key\030\001 \001(\005\022\035\n\005value\030\002 \001(\0132" +
      "\016.QuestStepData:\0028\001\"Y\n\rQuestStepData\022&\n\014" +
      "requirements\030\001 \003(\0132\020.RequirementData\022 \n\t" +
      "reactions\030\002 \003(\0132\r.ReactionDataB1\n com.re" +
      "is.game.resource.prototypeB\rQuestLogProt" +
      "ob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.reis.game.resource.prototype.RequirementProto.getDescriptor(),
          com.reis.game.resource.prototype.ReactionProto.getDescriptor(),
        }, assigner);
    internal_static_QuestLogData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QuestLogData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestLogData_descriptor,
        new java.lang.String[] { "QuestLog", });
    internal_static_QuestLogData_QuestLogEntry_descriptor =
      internal_static_QuestLogData_descriptor.getNestedTypes().get(0);
    internal_static_QuestLogData_QuestLogEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestLogData_QuestLogEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_QuestStepData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QuestStepData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestStepData_descriptor,
        new java.lang.String[] { "Requirements", "Reactions", });
    com.reis.game.resource.prototype.RequirementProto.getDescriptor();
    com.reis.game.resource.prototype.ReactionProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
