// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: questState.proto

package com.reis.game.resource.prototype;

public final class QuestStateProto {
  private QuestStateProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface QuestStateDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QuestStateData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    java.util.List<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry> 
        getQuestStatesList();
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry getQuestStates(int index);
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    int getQuestStatesCount();
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    java.util.List<? extends com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder> 
        getQuestStatesOrBuilderList();
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder getQuestStatesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code QuestStateData}
   */
  public  static final class QuestStateData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QuestStateData)
      QuestStateDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuestStateData.newBuilder() to construct.
    private QuestStateData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestStateData() {
      questStates_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuestStateData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                questStates_ = new java.util.ArrayList<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry>();
                mutable_bitField0_ |= 0x00000001;
              }
              questStates_.add(
                  input.readMessage(com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          questStates_ = java.util.Collections.unmodifiableList(questStates_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.QuestStateProto.QuestStateData.class, com.reis.game.resource.prototype.QuestStateProto.QuestStateData.Builder.class);
    }

    public static final int QUESTSTATES_FIELD_NUMBER = 1;
    private java.util.List<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry> questStates_;
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    public java.util.List<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry> getQuestStatesList() {
      return questStates_;
    }
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    public java.util.List<? extends com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder> 
        getQuestStatesOrBuilderList() {
      return questStates_;
    }
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    public int getQuestStatesCount() {
      return questStates_.size();
    }
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry getQuestStates(int index) {
      return questStates_.get(index);
    }
    /**
     * <code>repeated .QuestStateEntry questStates = 1;</code>
     */
    public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder getQuestStatesOrBuilder(
        int index) {
      return questStates_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < questStates_.size(); i++) {
        output.writeMessage(1, questStates_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < questStates_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, questStates_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.QuestStateProto.QuestStateData)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.QuestStateProto.QuestStateData other = (com.reis.game.resource.prototype.QuestStateProto.QuestStateData) obj;

      boolean result = true;
      result = result && getQuestStatesList()
          .equals(other.getQuestStatesList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getQuestStatesCount() > 0) {
        hash = (37 * hash) + QUESTSTATES_FIELD_NUMBER;
        hash = (53 * hash) + getQuestStatesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.QuestStateProto.QuestStateData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QuestStateData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QuestStateData)
        com.reis.game.resource.prototype.QuestStateProto.QuestStateDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.QuestStateProto.QuestStateData.class, com.reis.game.resource.prototype.QuestStateProto.QuestStateData.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.QuestStateProto.QuestStateData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getQuestStatesFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (questStatesBuilder_ == null) {
          questStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          questStatesBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateData_descriptor;
      }

      public com.reis.game.resource.prototype.QuestStateProto.QuestStateData getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.QuestStateProto.QuestStateData.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.QuestStateProto.QuestStateData build() {
        com.reis.game.resource.prototype.QuestStateProto.QuestStateData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.QuestStateProto.QuestStateData buildPartial() {
        com.reis.game.resource.prototype.QuestStateProto.QuestStateData result = new com.reis.game.resource.prototype.QuestStateProto.QuestStateData(this);
        int from_bitField0_ = bitField0_;
        if (questStatesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            questStates_ = java.util.Collections.unmodifiableList(questStates_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.questStates_ = questStates_;
        } else {
          result.questStates_ = questStatesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.QuestStateProto.QuestStateData) {
          return mergeFrom((com.reis.game.resource.prototype.QuestStateProto.QuestStateData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.QuestStateProto.QuestStateData other) {
        if (other == com.reis.game.resource.prototype.QuestStateProto.QuestStateData.getDefaultInstance()) return this;
        if (questStatesBuilder_ == null) {
          if (!other.questStates_.isEmpty()) {
            if (questStates_.isEmpty()) {
              questStates_ = other.questStates_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureQuestStatesIsMutable();
              questStates_.addAll(other.questStates_);
            }
            onChanged();
          }
        } else {
          if (!other.questStates_.isEmpty()) {
            if (questStatesBuilder_.isEmpty()) {
              questStatesBuilder_.dispose();
              questStatesBuilder_ = null;
              questStates_ = other.questStates_;
              bitField0_ = (bitField0_ & ~0x00000001);
              questStatesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getQuestStatesFieldBuilder() : null;
            } else {
              questStatesBuilder_.addAllMessages(other.questStates_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.QuestStateProto.QuestStateData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.QuestStateProto.QuestStateData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry> questStates_ =
        java.util.Collections.emptyList();
      private void ensureQuestStatesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          questStates_ = new java.util.ArrayList<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry>(questStates_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder> questStatesBuilder_;

      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry> getQuestStatesList() {
        if (questStatesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(questStates_);
        } else {
          return questStatesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public int getQuestStatesCount() {
        if (questStatesBuilder_ == null) {
          return questStates_.size();
        } else {
          return questStatesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry getQuestStates(int index) {
        if (questStatesBuilder_ == null) {
          return questStates_.get(index);
        } else {
          return questStatesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder setQuestStates(
          int index, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry value) {
        if (questStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestStatesIsMutable();
          questStates_.set(index, value);
          onChanged();
        } else {
          questStatesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder setQuestStates(
          int index, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder builderForValue) {
        if (questStatesBuilder_ == null) {
          ensureQuestStatesIsMutable();
          questStates_.set(index, builderForValue.build());
          onChanged();
        } else {
          questStatesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder addQuestStates(com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry value) {
        if (questStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestStatesIsMutable();
          questStates_.add(value);
          onChanged();
        } else {
          questStatesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder addQuestStates(
          int index, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry value) {
        if (questStatesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureQuestStatesIsMutable();
          questStates_.add(index, value);
          onChanged();
        } else {
          questStatesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder addQuestStates(
          com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder builderForValue) {
        if (questStatesBuilder_ == null) {
          ensureQuestStatesIsMutable();
          questStates_.add(builderForValue.build());
          onChanged();
        } else {
          questStatesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder addQuestStates(
          int index, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder builderForValue) {
        if (questStatesBuilder_ == null) {
          ensureQuestStatesIsMutable();
          questStates_.add(index, builderForValue.build());
          onChanged();
        } else {
          questStatesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder addAllQuestStates(
          java.lang.Iterable<? extends com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry> values) {
        if (questStatesBuilder_ == null) {
          ensureQuestStatesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, questStates_);
          onChanged();
        } else {
          questStatesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder clearQuestStates() {
        if (questStatesBuilder_ == null) {
          questStates_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          questStatesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public Builder removeQuestStates(int index) {
        if (questStatesBuilder_ == null) {
          ensureQuestStatesIsMutable();
          questStates_.remove(index);
          onChanged();
        } else {
          questStatesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder getQuestStatesBuilder(
          int index) {
        return getQuestStatesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder getQuestStatesOrBuilder(
          int index) {
        if (questStatesBuilder_ == null) {
          return questStates_.get(index);  } else {
          return questStatesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public java.util.List<? extends com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder> 
           getQuestStatesOrBuilderList() {
        if (questStatesBuilder_ != null) {
          return questStatesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(questStates_);
        }
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder addQuestStatesBuilder() {
        return getQuestStatesFieldBuilder().addBuilder(
            com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder addQuestStatesBuilder(
          int index) {
        return getQuestStatesFieldBuilder().addBuilder(
            index, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.getDefaultInstance());
      }
      /**
       * <code>repeated .QuestStateEntry questStates = 1;</code>
       */
      public java.util.List<com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder> 
           getQuestStatesBuilderList() {
        return getQuestStatesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder> 
          getQuestStatesFieldBuilder() {
        if (questStatesBuilder_ == null) {
          questStatesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder>(
                  questStates_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          questStates_ = null;
        }
        return questStatesBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QuestStateData)
    }

    // @@protoc_insertion_point(class_scope:QuestStateData)
    private static final com.reis.game.resource.prototype.QuestStateProto.QuestStateData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.QuestStateProto.QuestStateData();
    }

    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuestStateData>
        PARSER = new com.google.protobuf.AbstractParser<QuestStateData>() {
      public QuestStateData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QuestStateData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestStateData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestStateData> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.QuestStateProto.QuestStateData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QuestStateEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QuestStateEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 questId = 1;</code>
     */
    int getQuestId();

    /**
     * <code>int32 questStep = 2;</code>
     */
    int getQuestStep();
  }
  /**
   * Protobuf type {@code QuestStateEntry}
   */
  public  static final class QuestStateEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QuestStateEntry)
      QuestStateEntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use QuestStateEntry.newBuilder() to construct.
    private QuestStateEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private QuestStateEntry() {
      questId_ = 0;
      questStep_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private QuestStateEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              questId_ = input.readInt32();
              break;
            }
            case 16: {

              questStep_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.class, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder.class);
    }

    public static final int QUESTID_FIELD_NUMBER = 1;
    private int questId_;
    /**
     * <code>int32 questId = 1;</code>
     */
    public int getQuestId() {
      return questId_;
    }

    public static final int QUESTSTEP_FIELD_NUMBER = 2;
    private int questStep_;
    /**
     * <code>int32 questStep = 2;</code>
     */
    public int getQuestStep() {
      return questStep_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (questId_ != 0) {
        output.writeInt32(1, questId_);
      }
      if (questStep_ != 0) {
        output.writeInt32(2, questStep_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (questId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, questId_);
      }
      if (questStep_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, questStep_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry)) {
        return super.equals(obj);
      }
      com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry other = (com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry) obj;

      boolean result = true;
      result = result && (getQuestId()
          == other.getQuestId());
      result = result && (getQuestStep()
          == other.getQuestStep());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + QUESTID_FIELD_NUMBER;
      hash = (53 * hash) + getQuestId();
      hash = (37 * hash) + QUESTSTEP_FIELD_NUMBER;
      hash = (53 * hash) + getQuestStep();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QuestStateEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QuestStateEntry)
        com.reis.game.resource.prototype.QuestStateProto.QuestStateEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.class, com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.Builder.class);
      }

      // Construct using com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        questId_ = 0;

        questStep_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reis.game.resource.prototype.QuestStateProto.internal_static_QuestStateEntry_descriptor;
      }

      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry getDefaultInstanceForType() {
        return com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.getDefaultInstance();
      }

      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry build() {
        com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry buildPartial() {
        com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry result = new com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry(this);
        result.questId_ = questId_;
        result.questStep_ = questStep_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry) {
          return mergeFrom((com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry other) {
        if (other == com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry.getDefaultInstance()) return this;
        if (other.getQuestId() != 0) {
          setQuestId(other.getQuestId());
        }
        if (other.getQuestStep() != 0) {
          setQuestStep(other.getQuestStep());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int questId_ ;
      /**
       * <code>int32 questId = 1;</code>
       */
      public int getQuestId() {
        return questId_;
      }
      /**
       * <code>int32 questId = 1;</code>
       */
      public Builder setQuestId(int value) {
        
        questId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 questId = 1;</code>
       */
      public Builder clearQuestId() {
        
        questId_ = 0;
        onChanged();
        return this;
      }

      private int questStep_ ;
      /**
       * <code>int32 questStep = 2;</code>
       */
      public int getQuestStep() {
        return questStep_;
      }
      /**
       * <code>int32 questStep = 2;</code>
       */
      public Builder setQuestStep(int value) {
        
        questStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 questStep = 2;</code>
       */
      public Builder clearQuestStep() {
        
        questStep_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QuestStateEntry)
    }

    // @@protoc_insertion_point(class_scope:QuestStateEntry)
    private static final com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry();
    }

    public static com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<QuestStateEntry>
        PARSER = new com.google.protobuf.AbstractParser<QuestStateEntry>() {
      public QuestStateEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new QuestStateEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<QuestStateEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<QuestStateEntry> getParserForType() {
      return PARSER;
    }

    public com.reis.game.resource.prototype.QuestStateProto.QuestStateEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestStateData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestStateData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QuestStateEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QuestStateEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020questState.proto\"7\n\016QuestStateData\022%\n\013" +
      "questStates\030\001 \003(\0132\020.QuestStateEntry\"5\n\017Q" +
      "uestStateEntry\022\017\n\007questId\030\001 \001(\005\022\021\n\tquest" +
      "Step\030\002 \001(\005B3\n com.reis.game.resource.pro" +
      "totypeB\017QuestStateProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QuestStateData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QuestStateData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestStateData_descriptor,
        new java.lang.String[] { "QuestStates", });
    internal_static_QuestStateEntry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QuestStateEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QuestStateEntry_descriptor,
        new java.lang.String[] { "QuestId", "QuestStep", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
